global:
  image:
    tag: latest
server:
  replicas: 2
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      # ALB Ingress Group
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP  # Changed from HTTPS to HTTP
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      #alb.ingress.kubernetes.io/certificate-arn: 
      # Health check configuration
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP  # Changed from HTTPS to HTTP
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    hosts:
      - argocd.dns.com
    tls: []
  extraArgs:
    - --insecure
  nodeSelector:
    nodepool: eks-microservices
  tolerations: []
controller:
  replicas: 1
  nodeSelector:
    nodepool: eks-microservices
  tolerations: []
repoServer:
  replicas: 1
  nodeSelector:
    nodepool: eks-microservices
  tolerations: []
applicationSet:
  replicaCount: 1
  nodeSelector:
    nodepool: eks-microservices
  tolerations: []
configs:
  params:
    server.insecure: true
  cm:
    timeout.reconciliation: 180s
